version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.14"

formats: all

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .

submodules:
  include: all
  recursive: true
